### ISSUE TITLE
ModuleNotFoundError: No module named 'jack_mixer_c'

### ISSUE THREAD

**Issue by mxmilkiib** [jack-mixer/jack_mixer#88] opened 2020-12-17 00:37 UTC
I'm currently getting;
```
Traceback (most recent call last):
  File "/usr/bin/jack_mixer", line 40, in <module>
    import jack_mixer_c
ModuleNotFoundError: No module named 'jack_mixer_c'
```

**Comment by SpotlightKid** [comment] 2020-12-17 07:18
Is this on Arch? If you use the `jack_mixer-git` package, you need to rebuild & re-install after the switch to Python 3.9. The `jack_mixer` package in community was already bumped to version 14-3 for this reason.

**Comment by mxmilkiib** [comment] 2020-12-18 08:09
Yes. The bin package version works. I cleanbuilt -git from the AUR, same issue as above. Then I cloned and built, same error.

**Comment by SpotlightKid** [comment] 2020-12-18 10:36
Ok, I can reproduce the error with the `jack_mixer-git` package.

The Python C extension module somehow ends up in `/usr/lib/python3.9/site-packages/jack_mixer/jack_mixer_c.so` instead of `/usr/lib/python3.9/site-packages/jack_mixer_c.so`. I'm not sure why, I need to investigate.

**Comment by SpotlightKid** [comment] 2020-12-18 15:16
This is caused by commit f14c177f5bfc4681cd09c64c1a4c4da08f9c6f90.

For some reason, because the `AM_PATH_PYTHON` macro was moved into the `if test "$enable_gui" != "no"` block, autoconf now ignores overrididing the value of the `pkgpyexecdir` variable in [Makefile.am](https://github.com/jack-mixer/jack_mixer/blob/f14c177f5bfc4681cd09c64c1a4c4da08f9c6f90/Makefile.am#L56) and issues the following warning, which was unfortunately overlooked when checking PR #84 before merging it.

    Makefile.am:56: warning: pkgpyexecdir was already defined in condition TRUE, which includes condition ENABLE_GUI ...

(To be fair, the warning isn't very clear about what's going on.)

This causes `pkgpyexecdir` to remain at the default value `‘$(pythondir)/$(PACKAGE)’`. Thus `jack_mixer_c.so` will be installed to `/usr/lib/python3.9/site-packages/jack_mixer/jack_mixer_c.so` and `jack_mixer.py` will fail to import it.

This just highlights, IMO, that we should get rid of autotools asap, since it's just too hard to understand what it does.

**Closed** 2020-12-18 16:13 UTC
Labels: bug, confirmed

**Comment by mxa** [comment] 2021-02-17 00:14
I have this issue with the current git version

```
jack_mixer
Traceback (most recent call last):
  File "/usr/local/bin/jack_mixer", line 43, in <module>
    import jack_mixer_c
ModuleNotFoundError: No module named 'jack_mixer_c'

```
A regression?

**Comment by SpotlightKid** [comment] 2021-02-17 12:49
@mxa: can't reproduce that (commit 5a7c8b0).

Anyway, the git repo will be going through some restructuring with the upcoming merge of #106 anyway, so there isn't much point in examining this now.
